### ISSUE TITLE
v1.0.2 does not find installed versions of deno

### ISSUE THREAD

**Issue by RMcNeely** [axetroy/dvm#15]
After installing dvm and installing versions 0.31.0 and 0.30.0 of deno,  I am unable find them with dvm. They are listed in the .dvm folder however it appears that dvm itself cannot find the versions. When I do try `dvm current` I get the 'You haven't used Deno yet' error message.

Using elementaryOS 5.1 Hera (Ubuntu 18.04.3)

**Comment by axetroy** [comment]
hi.

Have you set the environment variables to $PATH?

```bash
# ~/.bash_profile
export PATH="$PATH:~/bin"

export PATH="$PATH:~/.deno/bin"
```

Then check if the file exists

```bash
ls -lh ~/.deno/bin/deno
```

**Comment by RMcNeely** [comment]
ahhh there's no instructions about adding the second export. If I add that to my PATH then everything is fine.

**Comment by axetroy** [comment]
The second export is Deno officially designated.

```bash
export PATH="$PATH:~/.deno/bin"
```

yeah. this is not specified in the documentation.

I will close this issue and update the documentation later

thank you for your feedback

**Comment by RMcNeely** [comment]
I see your documentation also points to "latest" as an example of what you can install which I see was removed in another issue. You may want to also remove that example.

**Comment by axetroy** [comment]
"latest" for install is still working for now.

```bash
dvm install latest
```
