### ISSUE TITLE
error when wget is not available.

### ISSUE THREAD

**Issue by multics** [axetroy/dvm#21]
This is a good start for deno version manager.

I am on macOS, I've not installed `wget` and **not plan** to install `wget` too.

```
bash: line 48: wget: command not found
```

Please do not assume and use `wget`. There is `curl`, and the readme use `curl -fsSL https://raw.githubusercontent.com/axetroy/dvm/master/install.sh` already.

**Comment by axetroy** [comment]
Now it no longer use the wget command. Thx
