### ISSUE TITLE
[Question] What happened to the install latest feature?

### ISSUE THREAD

**Issue by lucasvazq** [axetroy/dvm#28]
The dvm install latest command don't work.
```shell
➜ dvm install "latest"
✖ get remote tar filename fail: Invalid Semantic Version
```

In the following comment: https://github.com/axetroy/dvm/issues/10#issuecomment-570784496, @axetroy mentions that it was decided to remove this feature, but some mentions to them keep in the code and in the README.md file

**Comment by lucasvazq** [comment]
@axetroy Why was it decided to remove the latest feature?

**Comment by emmanuelnk** [comment]
Same issue. Also curious as to why it was removed? @axetroy ?? 
It's a breaking change. 

Anyway, to get around it. I'm doing `dvm install $(dvm ls-remote | tail -1) `

**Comment by axetroy** [comment]
Well, I didn’t expect anyone to use this

At first, I wanted to remove it only because I wanted people to install the specified version, which was clear and consistent with other commands.

I am considering whether I should rollback

**Comment by emmanuelnk** [comment]
I think it's important to keep this feature (unless it caused some other problems I am unaware of)

A lot of automated scripts will want to use dvm to install the latest version of Deno using `latest` tag.
