### ISSUE TITLE
Unable to use deno: dvm use fails to set current dvm version

### ISSUE THREAD

**Issue by OACDesigns** [axetroy/dvm#63]
I'm using the latest version v1.3.10, on a Mac M1 with oh-my-zsh as my shell.   
I have done `dvm install latest` which installs `v1.18.2` 
and then do `dvm use v1.18.2` which prints `Currently using Deno v1.18.2`.

However I am unable to run `deno -V`. Deno is simply not found and running `dvm current` prints `You haven't used Deno yet.`.

Is there something in the setup that I'm missing? was something supposed to be added to my PATH?

**Comment by axetroy** [comment]
Yes. you need to put `$HOME/.deno/bin` into your $PATH

**Comment by axetroy** [comment]
Sorry I didn't write in README. now it updates
