### ISSUE TITLE
install dvm

### ISSUE THREAD

**Issue by ghost** [axetroy/dvm#98]
Following the steps on README, I did the following to install `dvm` but unsuccessfully:

- `curl -fsSL https://github.com/release-lab/install/raw/v1/install.sh | bash -s -- -r=axetroy/dvm`
- got error: 
    - `INFO: file name is not specified, use 'dvm'
INFO: if you want to specify the name of the executable, set flag --exe=name`

## System
OS: Ubuntu 22.04
Kernel: 5.19

**Comment by atjn** [comment]
I also tried this on Ubuntu 22.04 on kernel 6.4.6, and got the same problem. I don't think the error you are showing above is actually the problem, it just seems to not work at all. AFAICT nothing was downloaded and installed.
